example/federalist.toml, package-lock.json, package.json, src/index.js, static/basic.css, static/index.html, webpack.config.js
This is a breaking JS change, but nobody uses Stork yet so it's ok.
- Adds Handlebars as a JS dependency for compiling the template.
- Standardizes model vs view handling in JS.
- Does a lot better job adding and removing elements from the DOM, which should fix #2 .
- Adds optional config variable to the `register` method to enable or disable the new progress bar feature
=> Enhance the Javascript UI

test/static/basic.css
=> Change `.stork-result a` selector so colors work

.vscode/launch.json, js/index.js, src/index_versions/v2/search.rs, src/index_versions/v2/structs.rs, src/searcher/mod.rs, test/static/basic.css
=> Handle, highlight, and sort multi-word queries

js/index.js, js/pencil.js, package.json, src/config/mod.rs, src/index_versions/v2/search.rs, src/index_versions/v3/builder.rs, src/index_versions/v3/search.rs, src/index_versions/v3/structs.rs, src/searcher/mod.rs, test/3b1b-config/3b1b.toml, test/static/basic.css, test/static/index.html
Also adds an optional configuration option to determine how much a result should get "boosted" in the list, based on search results found in titles
=> Index content in titles

js/config.ts, js/entity.ts, js/index.js, js/indexLoader.ts, js/pencil.js, js/util.ts, package.json, test/static/basic.css, tsconfig.json, webpack.config.js
- Creates Entity TS class
- Brings the `domUpdate` function into that Entity class
- Also extracts things into the `indexLoader` module
- Primes the loading interface when it starts downloading (instead of on progress) so that users have more visual feedback when the index is loading
=> Use keyboard to navigate results

.gitignore, .travis.yml, jest.config.js, js/config.test.ts, js/config.ts, js/index.js, package.json, yarn.lock
- Calculates code coverage and (hopefully) uploads to codecov
- Adds a test for the config module
=> Add Jest test framework

js/config.ts, js/entity.ts, src/config/mod.rs, src/index_versions/v3/builder/fill_containers.rs, src/index_versions/v3/builder/mod.rs
=> Configure minimum prefix/search string length with ideograph consideration

Cargo.lock, Cargo.toml, package.json
This reverts commit 083fe54cda471ac021c031c3e7468d8818aba2ba.
=> Revert "Change version (#86)"

src/index_versions/v3/builder/fill_containers.rs
=> Don't break loop if an unnormalizable word is found

codecov.yml
based on https://github.com/jameslittle230/stork/pull/98#issuecomment-751813011
=> Bump coverage to 57%

src/index_versions/v3/search/entry_and_intermediate_excerpts.rs, src/index_versions/v3/search/mod.rs, src/index_versions/v3/structs.rs
=> Fix highlight offsets when excerpt contains multi-byte characters

src/index_versions/v3/builder/annotated_words_from_string.rs, src/index_versions/v3/builder/errors.rs, src/index_versions/v3/builder/fill_containers.rs, src/index_versions/v3/builder/mod.rs, src/index_versions/v3/builder/word_list_generators/mod.rs, src/index_versions/v3/search/mod.rs, src/lib.rs
=> Helpfully handle hyphens when generating and searching through an index

js/entity.ts, js/entityDom.test.ts, js/entityDom.ts, js/entityManager.ts, js/indexLoader.ts, js/util.ts, test/static/index.html
This:
- Fixes #116 
- Fixes #109 
- Removes some stray console output
- Fixes error states after loading the index so it doesn't try to load an index that's a 404 page
=> Fix some Javascript bugs that have popped up

Cargo.lock, Cargo.toml, benches/basic.rs, package.json, readme.md, scripts/build.sh, scripts/develop.sh, scripts/download_test_corpora.sh, scripts/serve.sh, src/index_versions/v3/builder/mod.rs, src/index_versions/v3/builder/nudger.rs, test/federalist-config/federalist-debug.toml, test/federalist-config/federalist-expanded.toml, test/federalist-config/federalist-min.toml, test/federalist-config/federalist.toml
- Add benchmarks
- Improve getting-started experience by refactoring yarn scripts and adding info to the readme
=> Improve development experience

Cargo.lock, Cargo.toml, src/bin/stork/argparse.rs, src/bin/stork/main.rs, src/config/config_read_err.rs, src/config/mod.rs
Closes #142 
Usage:
```bash
$ cat ./my-config-file.toml | stork --build
```
=> Read TOML configuration from stdin

js/loaders/wasmLoader.ts, js/main.ts, src/wasm.rs
for debugging the state of the JS module while it's on the page!
=> Add debug method to JS interface

js/config.ts, js/entity.ts
=> Allow user to configure result noun

js/entityDom.ts, js/resultToListItem.test.ts, js/resultToListItem.ts, local-dev/index.html, themes/basic.css, themes/dark.css, themes/flat.css
=> Use CSS Variables to power themes

src/bin/stork/main.rs
=> Only read stdin if requested from the command line option

Cargo.lock, stork-config/Cargo.toml, stork-config/src/errors.rs, stork-config/src/file.rs, stork-config/src/lib.rs
=> Accept JSON as possible config format

changelog.md, stork-index-v3/src/build/fill_containers.rs, stork-index-v3/src/build/mod.rs
=> Fix crash when input includes words longer than 128 characters

Cargo.lock, changelog.md, stork-cli/Cargo.toml, stork-cli/src/clap.rs, stork-cli/src/display_timings.rs, stork-cli/src/errors.rs, stork-cli/src/main.rs, stork-cli/src/pretty_print_search_results.rs, stork-config/src/file.rs, stork-config/src/lib.rs, stork-index-v3/src/build/errors.rs, stork-index-v3/src/build/fill_intermediate_entries/data_source_readers/url_data_source_reader.rs, stork-index-v3/src/build/fill_intermediate_entries/word_list_generators/markdown_word_list_generator.rs, stork-index-v3/src/build/mod.rs, stork-index-v3/src/write.rs, stork-lib/src/lib.rs, stork-wasm/src/lib.rs
Also fixes the `--timing` flag
=> Add new search result output format

codecov.yml, stork-cli/src/io.rs
=> Fix regression when reading from stdin

themes/basic.css, themes/dark.css, themes/flat.css
=> Compensate for border radius when displaying progress bar

changelog.md, stork-lib/src/index_v3/build/errors.rs, stork-lib/src/index_v3/build/fill_intermediate_entries/mod.rs, stork-lib/src/index_v3/build/mod.rs
=> Display a list of document errors if all files fail to be indexed

changelog.md, js/resultToListItem.test.ts, js/resultToListItem.ts, justfile, local-dev/index.html, local-dev/test-configs/federalist-zero.toml, stork-cli/src/main.rs, stork-lib/src/index_v3/build/fill_containers.rs, stork-lib/src/index_v3/build/mod.rs, stork-lib/src/index_v3/mod.rs, stork-lib/src/index_v3/search/entry_and_intermediate_excerpts.rs, stork-lib/src/index_v3/search/mod.rs, themes/basic.css, themes/dark.css, themes/edible-dark.css, themes/edible.css, themes/flat.css
=> Optimize index size if excerpts_per_result is 0
