jameslittle230/stork

Cargo.lock
Cargo.toml
js/config.js
js/dom.js
js/index.js
js/pencil.js
package.json
src/index_versions/v2/builder.rs
src/index_versions/v2/scores.rs
src/index_versions/v2/search.rs
yarn.lock

Handlebars is far too big a dependency for the limited functionality I'm getting from it. Let's just use template strings instead.
This does mean that the `listItemTemplateString` config key is no more, and that people (for now) can't customize the elements being added to the DOM. This would technically be a breaking change if anyone were using Stork.
I think we'll need to make sure that the content is being appropriately escaped; in other words, I think this is vulnerable as-is if the index content contains malicious content.

Refactor JS to remove Handlebars

---

src/index_versions/v3/builder/mod.rs

Don’t break out of loop if you find an empty word

---

src/index_versions/v3/builder/fill_intermediate_entries.rs

My input config had 118,000 file object - each with DataSource::Contents - so we were spending tons (n * n) of time cloning here when it's not necessary
By hoisting the clone out of the loop and mutating thereafter, we avoid the expensive cloning.
This reduced my index build time from just under 3 hours to 55 seconds

Lift per_file_input_config outside of loop to avoid a potentially expensive clone

---

js/entityDom.ts

Resolves #92 
Since this project uses TypeScript, using `typeof` to check types instead of relying on the compiler can cause some tricky errors, such as the one described in #92. This change changes the type checks in `entityDom.ts` to be null checks, which is a more robust way of checking for `undefined`.
A nice side-effect of this is that it obviates the need for some of the manual `assert` statements, since the compiler verifies that type signature for us.

Change typeof checks to null checks.

---

webpack.config.js

This prevents Webpack from erroring if one of the test index files can’t be found, which is nice since they’re all technically optional

Copy *.st instead of specific index files

---

src/config/file.rs
src/index_versions/v3/builder/fill_intermediate_entries.rs
src/index_versions/v3/builder/mod.rs
src/index_versions/v3/builder/word_list_generators/html_word_list_generator.rs
src/index_versions/v3/builder/word_list_generators/mod.rs
src/lib.rs

In #105, @fauno points out that a file that cannot be indexed will fail the entire indexing process, and points out an issue with this methodology:
> The issue is that it doesn't tell me which page is missing it. Could it tell the path and maybe even skip the page?
This PR changes the indexing behavior so that if a word list generation error is encountered, the code looping through each file collects that error and associates it with the failing file, then prints out the list of errors during indexing, without failing the entire indexing process:
```
2 errors while indexing files:
- Error indexing `myFile.html`: HTML selector `.article` is not present in the file.
- Error indexing `myOtherFile.txt`: The file could not be found
```
This should clarify what is failing and why.
To fully fix …

Collect and display indexing errors instead of failing early

---

src/index_versions/v3/builder/errors.rs
src/index_versions/v3/builder/mod.rs
src/index_versions/v3/builder/word_list_generators/mod.rs
src/lib.rs

- Fixes a bug where file parse errors were being printed twice (whoops!)
- Returns an index generation error (and errors out nicely) if none of the files are valid, instead of panicking with a divide-by-zero error

Return an index generation error if there are no valid files

---

js/entityDom.test.ts
js/main.ts
js/wasmLoader.ts
js/wasmQueue.ts
test/static/index.html
webpack.config.js

Allow users to define a custom WASM URL.
This will add a "use at your own risk" kind of situation, since I won't be able to verify that the WASM loaded is the right WASM built to work with that version of the Javascript. However, this is required to implement self-hosting Stork, so the benefits outweigh the costs here. I'll add documentation to make it clear that you're taking your frontend into your own hands if you do this.
This PR closes #101.

Allow user to define custom WASM url in stork.initialize()

---

.prettierignore

Hi! First-time contributor here 👋 
<br>
Add a `.prettierignore` file so that Prettier only operates on the `/js` directory.
(TIL: about negative patterns — https://github.com/prettier/prettier/issues/3328)
<br>
This closes https://github.com/jameslittle230/stork/issues/136

Restrict Prettier to the /js directory

---

scripts/build.sh
scripts/generate_stats.py

Rewrite stats script to run benchmarks via `cargo criterion` and output JSON, fixing up a launchtime pain point.

Improve build stats script

---

Cargo.lock
Cargo.toml
js/entityManager.ts
scripts/build.sh
src/bin/stork/display_timings.rs
src/bin/stork/main.rs
src/bin/stork/test_server/mod.rs
src/config/file.rs
src/index_versions/v3/builder/fill_intermediate_entries.rs
src/index_versions/v3/builder/frontmatter.rs
src/index_versions/v3/builder/mod.rs
src/index_versions/v3/builder/word_list_generators/html_word_list_generator.rs
src/index_versions/v3/builder/word_list_generators/mod.rs
src/index_versions/v3/mod.rs
src/index_versions/v3/search/entry_and_intermediate_excerpts.rs
src/lib.rs
test/bowdoin-orient-config/bowdoin-orient.toml
test/web.toml

I've been working on this on [Twitch](https://twitch.tv/jameslittle230)! This feature will probably go out in 1.2.0.
Closes #11

Index content from the web

---

js/pencil.ts

Use the `<mark>` tag to highlight the search result, to increase semantics. 
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark#usage_notes second bullet point.

Use semantic HTML for search highlight

---

src/config/file.rs
src/config/mod.rs
src/index_versions/v3/builder/fill_intermediate_entries.rs
src/index_versions/v3/builder/mod.rs
test/bowdoin-orient-config/bowdoin-orient.toml

Now, the config file can look like:
```toml
[input]
html_selector = "main > article.post > .single__content"
[[input.files]]
url = "https://bowdoinorient.com/2021/02/19/from-zoom-hangouts-to-soup-cans-bowdoins-crew-team-gets-creative-during-social-distancing/"
title = "From Zoom hangouts to soup cans: Bowdoin’s crew team gets creative during social distancing"
[[input.files]]
url = "https://bowdoinorient.com/2021/02/19/pond-hockey-until-watson-opens-womens-hockey-stays-focused-on-virtual-team-bonding/"
title = "Pond hockey: until Watson opens women’s hockey stays focused on virtual team bonding"
[[input.files]]
url = "https://bowdoinorient.com/2021/02/19/embracing-technology-and-social-media-bowdoin-athletics-masters-new-tools-for-recruiting/"
title = "Embracing technology and social …
```

If src_url is missing from file, assume value is url field instead

---

readme.md

Hosting js files locally is not any slower compared to CDNs and may be even faster because all modern browsers separate caches by domain.

Remove inaccurate "optimal"

---

src/bin/stork/main.rs

- Hadn't gotten all the instances where a stdin read was blocking
- I was also using the wrong method to read from stdin 🤦 
- I might just remove the stdin functionality altogether in 2.0.0

_Actually_ fixes the stdin block

---

stork-cli/Cargo.toml

Rename cli binary to `stork` from default `stork-cli`

---

changelog.md
stork-index-v3/src/search/entry_and_intermediate_excerpts.rs

Fixes #236.
This is a hairy part of the code, and highlighting still isn't up to par, but this will at least stop the searcher from crashing as described in the issue.

Use the indexer's string split algorithm

---

stork-lib/src/index_v3/build/fill_containers.rs
stork-lib/src/index_v3/build/fill_stems.rs
stork-lib/src/index_v3/build/mod.rs
stork-lib/src/index_v3/mod.rs
stork-lib/src/index_v3/search/mod.rs

Fixes #261 
```sh
❯ while TRUE; cargo run -- build --input local-dev/test-configs/federalist.toml --output test.st 2> /dev/null && sha256sum test.st; end
05ece8e36d4c1abc4362f3969c304288a26500a81df05d37f324ba709581e955  test.st
05ece8e36d4c1abc4362f3969c304288a26500a81df05d37f324ba709581e955  test.st
05ece8e36d4c1abc4362f3969c304288a26500a81df05d37f324ba709581e955  test.st
05ece8e36d4c1abc4362f3969c304288a26500a81df05d37f324ba709581e955  test.st
```
This is achieved by using a BTreeMap instead of a Hashmap in the Index data structure. This looks like it slows down build times a lot; I'm not sure what effect it has on search times.
Alternatively, I could only convert to a BTreeMap when it comes time to serialize, as described in https://stackoverflow.com/a/42723390 - let's see how metrics …

Convert all HashMap usage to BTreeMap

---

Cargo.lock
changelog.md
stork-cli/Cargo.toml
stork-cli/src/clap.rs
stork-cli/src/errors.rs
stork-cli/src/main.rs
stork-cli/src/test_server/index.html
stork-cli/src/test_server/mod.rs

Problems:
- The feature was hidden behind a Cargo `feature` that didn't exist, so it was never being compiled in
- The feature was out of date and didn't compile as-is
- The demo webpage referenced old CDN assets
- The value of the `index_path` command line argument wasn't being extracted properly since I was querying it with the incorrect string `index`
Fixes #269

Fix the test server

---

changelog.md
js/config.ts
js/entity.ts

Transforming result URLs allows the user to build sites that are relocatable rather anchored on the site root (for instance, by prepending the resulting URL with the relative path to the root directory).
I'm sure other uses exist too, but this is what I need it for.
Thanks

Add transformResultUrl callback to JS API

---

Cargo.lock
changelog.md
stork-lib/Cargo.toml
stork-lib/src/index_v3/build/fill_intermediate_entries/data_source_readers/mod.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/mod.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/word_list_generators/markdown_word_list_generator.rs

Fix crash when parsing Markdown content

---

themes/basic.css
themes/dark.css
themes/edible-dark.css
themes/edible.css
themes/flat.css

Add a CSS rule to center the X in the stork-close-button
Before
After

Center SVG x in stork-close-button

---

.github/workflows/ci-on-push.yml
stork-cli/src/clap.rs
stork-cli/src/io.rs
stork-cli/src/main.rs
stork-cli/src/pretty_print_search_results.rs
stork-cli/src/test_server/mod.rs
stork-lib/src/config/mod.rs
stork-lib/src/config/srt.rs
stork-lib/src/config/stemming.rs
stork-lib/src/index_v2/search.rs
stork-lib/src/index_v3/build/errors.rs
stork-lib/src/index_v3/build/fill_containers.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/data_source_readers/filepath_data_source_reader.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/frontmatter.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/mod.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/word_list_generators/html_word_list_generator.rs
stork-lib/src/index_v3/build/fill_intermediate_entries/word_list_generators/srt_word_list_generator.rs
stork-lib/src/index_v3/build/intermediate_entry.rs
stork-lib/src/index_v3/build/mod.rs
stork-lib/src/index_v3/search/entry_and_intermediate_excerpts.rs
stork-lib/src/lib.rs
stork-wasm/src/lib.rs

- minutes_and_seconds is a supported config value
- template string expects `{}` instead of `{ts}`
Closes #330

Fix timestamp formatting to match documentation
